# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LLF(object):
    def setupUi(self, LLF):
        LLF.setObjectName("LLF")
        LLF.resize(715, 524)
        self.original_video = QtWidgets.QLabel(LLF)
        self.original_video.setGeometry(QtCore.QRect(20, 120, 261, 241))
        self.original_video.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.original_video.setAlignment(QtCore.Qt.AlignCenter)
        self.original_video.setObjectName("original_video")
        self.enhanced_video = QtWidgets.QLabel(LLF)
        self.enhanced_video.setGeometry(QtCore.QRect(320, 120, 261, 241))
        self.enhanced_video.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.enhanced_video.setAlignment(QtCore.Qt.AlignCenter)
        self.enhanced_video.setObjectName("enhanced_video")
        self.startButton = QtWidgets.QPushButton(LLF)
        self.startButton.setGeometry(QtCore.QRect(30, 60, 161, 23))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(LLF)
        self.stopButton.setGeometry(QtCore.QRect(220, 60, 171, 23))
        self.stopButton.setObjectName("stopButton")
        self.enhanceButton = QtWidgets.QPushButton(LLF)
        self.enhanceButton.setGeometry(QtCore.QRect(420, 60, 161, 23))
        self.enhanceButton.setObjectName("enhanceButton")
        self.label = QtWidgets.QLabel(LLF)
        self.label.setGeometry(QtCore.QRect(20, 390, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LLF)
        self.label_2.setGeometry(QtCore.QRect(80, 400, 371, 51))
        self.label_2.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LLF)
        self.label_3.setGeometry(QtCore.QRect(30, 16, 551, 31))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(LLF)
        QtCore.QMetaObject.connectSlotsByName(LLF)

    def retranslateUi(self, LLF):
        _translate = QtCore.QCoreApplication.translate
        LLF.setWindowTitle(_translate("LLF", "Dialog"))
        self.original_video.setText(_translate("LLF", "原视频将显示在这里"))
        self.enhanced_video.setText(_translate("LLF", "系统处理后的视频将显示在这里"))
        self.startButton.setText(_translate("LLF", "start"))
        self.stopButton.setText(_translate("LLF", "stop"))
        self.enhanceButton.setText(_translate("LLF", "enhance"))
        self.label.setText(_translate("LLF", "识别结果："))
        self.label_2.setText(_translate("LLF", "结束处理后识别出的人脸名字将显示在这里"))
        self.label_3.setText(_translate("LLF", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">低质人脸增强和识别系统</span></p></body></html>"))
